version: "3.8"

services:
  db:
    image: mysql:8
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: greendog
      MYSQL_ROOT_PASSWORD: cecgil
      MYSQL_USER: cecgil
      MYSQL_PASSWORD: cecgil

  adminer:
    image: adminer
    ports:
      - "8000:8080"
